// Code generated by "stringer -type=DomainType -linecomment"; DO NOT EDIT.

package api

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[DomainTypeCloudflare-1]
	_ = x[DomainTypeHostname-2]
	_ = x[DomainTypeWildcard-3]
}

const _DomainType_name = "cloudflarehostnamewildcard"

var _DomainType_index = [...]uint8{0, 10, 18, 26}

func (i DomainType) String() string {
	i -= 1
	if i < 0 || i >= DomainType(len(_DomainType_index)-1) {
		return "DomainType(" + strconv.FormatInt(int64(i+1), 10) + ")"
	}
	return _DomainType_name[_DomainType_index[i]:_DomainType_index[i+1]]
}
