// Code generated by "stringer -type=DomainStatus -linecomment"; DO NOT EDIT.

package api

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[DomainStatusPending-0]
	_ = x[DomainStatusSuccess-1]
	_ = x[DomainStatusError-2]
	_ = x[DomainStatusVerify-3]
}

const _DomainStatus_name = "pendingsuccesserrorverify"

var _DomainStatus_index = [...]uint8{0, 7, 14, 19, 25}

func (i DomainStatus) String() string {
	if i < 0 || i >= DomainStatus(len(_DomainStatus_index)-1) {
		return "DomainStatus(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _DomainStatus_name[_DomainStatus_index[i]:_DomainStatus_index[i+1]]
}
