// Code generated by "stringer -type=DomainPlan -linecomment"; DO NOT EDIT.

package api

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[DomainPlanFree-0]
	_ = x[DomainPlanBasic-1]
	_ = x[DomainPlanAdvanced-2]
}

const _DomainPlan_name = "freebasicadvanced"

var _DomainPlan_index = [...]uint8{0, 4, 9, 17}

func (i DomainPlan) String() string {
	if i < 0 || i >= DomainPlan(len(_DomainPlan_index)-1) {
		return "DomainPlan(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _DomainPlan_name[_DomainPlan_index[i]:_DomainPlan_index[i+1]]
}
