name: Build
on:
  push:
    branches:
    - master
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-go@v2
      with:
        go-version: "^1.16"
    - run: go build -o deploys .
    - uses: actions/upload-artifact@v2
      with:
        name: deploys
        path: deploys
